import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parse } from '../../dsl/parser.ts';
import { exportDDL } from '../export/ddl-writer.ts';
import { importSql } from '../import/ddl-parser.ts';

const ecommerce = parse(
  readFileSync(resolve(process.cwd(), 'public/samples/ecommerce.pgl'), 'utf8'),
).schema;

describe('DDL export', () => {
  const ddl = exportDDL(ecommerce);

  it('emits CREATE TYPE for enums', () => {
    expect(ddl).toContain(
      "CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');",
    );
  });

  it('emits GENERATED ... AS IDENTITY, never serial', () => {
    expect(ddl).toContain('GENERATED BY DEFAULT AS IDENTITY');
    expect(ddl).not.toMatch(/\bserial\b/i);
  });

  it('emits FKs as ALTER TABLE ADD CONSTRAINT after the tables', () => {
    const fkIdx = ddl.indexOf('ADD CONSTRAINT');
    const tableIdx = ddl.indexOf('CREATE TABLE');
    expect(fkIdx).toBeGreaterThan(tableIdx);
    expect(ddl).toContain('FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
  });

  it('emits composite PRIMARY KEY inline', () => {
    expect(ddl).toContain('PRIMARY KEY (order_id, product_id)');
  });

  it('emits partial + expression indexes', () => {
    expect(ddl).toContain('WHERE deleted_at is null');
    expect(ddl).toContain('USING gin');
  });
});

describe('SQL round-trip stability (§17)', () => {
  it('exportDDL → importSql preserves the schema shape', () => {
    const ddl = exportDDL(ecommerce);
    const { schema: back, diagnostics } = importSql(ddl);
    expect(diagnostics.filter((d) => d.severity === 'error')).toEqual([]);

    const shape = (s: typeof ecommerce) => ({
      tables: s.tables.length,
      columns: s.tables.reduce((a, t) => a + t.columns.length, 0),
      pkTables: s.tables.filter((t) => t.primaryKey.length > 0).length,
      rels: s.relationships.length,
      indexes: s.indexes.length,
      enums: s.enums.length,
    });
    expect(shape(back)).toEqual(shape(ecommerce));
  });

  it('is idempotent across a second export/import', () => {
    const once = importSql(exportDDL(ecommerce)).schema;
    const twice = importSql(exportDDL(once)).schema;
    expect(twice.tables.length).toBe(once.tables.length);
    expect(twice.relationships.length).toBe(once.relationships.length);
    // column types stable
    const t1 = once.tables.find((t) => t.name === 'orders')!;
    const t2 = twice.tables.find((t) => t.name === 'orders')!;
    expect(t2.columns.map((c) => c.type.name)).toEqual(t1.columns.map((c) => c.type.name));
  });
});
