// Plain TypeScript interfaces + a Kysely-compatible Database interface. PRD §11.
import type { Column, Schema } from '../model/types.ts';
import { effectiveNotNull, enumOf, enumTypeName, pascalCase, singular } from './util.ts';

/** Map a Postgres column to a TypeScript type (ignoring nullability). */
export function tsType(schema: Schema, col: Column): string {
  const en = enumOf(schema, col);
  let base: string;
  if (en) {
    base = en.values.map((v) => JSON.stringify(v)).join(' | ');
  } else {
    base = scalarTs(col.type.name);
  }
  const arr = '[]'.repeat(col.type.arrayDims);
  // wrap unions in parens before an array suffix
  const needsParen = col.type.arrayDims > 0 && base.includes(' | ');
  return `${needsParen ? `(${base})` : base}${arr}`;
}

function scalarTs(name: string): string {
  switch (name) {
    case 'smallint':
    case 'integer':
    case 'real':
    case 'double precision':
    case 'smallserial':
    case 'serial':
    case 'bigserial':
      return 'number';
    case 'bigint':
    case 'numeric':
    case 'decimal':
    case 'money':
      return 'string'; // preserve precision
    case 'boolean':
      return 'boolean';
    case 'json':
    case 'jsonb':
      return 'unknown';
    case 'date':
    case 'timestamp':
    case 'timestamptz':
    case 'time':
    case 'timetz':
      return 'Date';
    case 'bytea':
      return 'Uint8Array';
    default:
      return 'string';
  }
}

export function generateTypeScript(schema: Schema): string {
  const out: string[] = ['// Generated by Pglass — plain interfaces + a Kysely Database type.', ''];

  for (const en of [...schema.enums].sort((a, b) => a.name.localeCompare(b.name))) {
    const union = en.values.map((v) => JSON.stringify(v)).join(' | ');
    out.push(`export type ${enumTypeName(en.name)} = ${union};`);
  }
  if (schema.enums.length) out.push('');

  for (const table of schema.tables) {
    const iface = pascalCase(singular(table.name));
    out.push(`export interface ${iface} {`);
    for (const col of table.columns) {
      const optional = effectiveNotNull(table, col) ? '' : ' | null';
      out.push(`  ${propName(col.name)}: ${tsType(schema, col)}${optional};`);
    }
    out.push('}', '');
  }

  // Kysely-style Database registry, keyed by real table name.
  out.push('export interface Database {');
  for (const table of schema.tables) {
    out.push(`  ${propName(table.name)}: ${pascalCase(singular(table.name))};`);
  }
  out.push('}', '');

  return out.join('\n');
}

function propName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
